cc_library(
    name = "time_util",
    hdrs = ["time_util.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "timer",
    srcs = ["timer.cc"],
    hdrs = ["timer.h"],
    deps = [":time_util"],    
    visibility = ["//visibility:public"],
)
