load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
	name = "main",
	srcs = ["main.cc"],
	deps = [
	#	"child/name",
		"//third_party/eventpp:eventpp",
	],
)

#cc_library(
#	name = "",
#	srcs = [""],
#	hdrs = [""],
#)
